### PR TITLE
Ignore private package

### PR DESCRIPTION
**Pull request by yudppp**
Hi @twada 

I don't want to include private packages.
Therefore I made them Ignore a private packages license.

Occurred small breaking changes.

Thanks.

### CODE REVIEW

**Comment by twada** [comment]
@yudppp Oh I missed that point. Thanks a lot!
I'll review this PR now.

**Comment by twada** [comment]
@yudppp LGTM. Thank you for your great contribution!

**Comment by yudppp** [comment]
Thanks:)

**Comment by yasaichi** [comment]
:+1:

**Comment by twada** [comment]
Thanks. I'll cut a new release tomorrow.

**Pull request merged**
